### ISSUE TITLE
Console output on running VOC 

### ISSUE THREAD

**Issue by rixx** [beeware/voc#947]
When running `voc somefile.py` it would be nice to receive some feedback, like `Compiled example.py to python/example.class`, or even just `./python/example.class`, if you want to go for machine-readable output.

**Comment by freakboy3742** [comment]
Interesting; I was broadly trying to mimic the GCC interface here - i.e., say nothing unless there's a problem. As it currently stands, there is a -v (and -vv, -vvv) options if you want more info about the compilation process; I'm interested in what about the experience led you to need/expect more output by default

**Comment by rixx** [comment]
The GCC behaviour is a fair point, and a better argument than my gut feeling.

> I'm interested in what about the experience led you to need/expect more output by default

I think it's just that most tools I interact with nowadays provide stdout feedback by default, so not seeing anything was a surprise. But I agree that consistent interfaces are good, and with having -v there this is a non-issue.
