### ISSUE TITLE
beekeeper badge isn't displayed due to bad image link

### ISSUE THREAD

**Issue by ikostan** [beeware/voc#957]
### Title: beekeeper badge isn't displayed due to bad image link

**Step by step:**

1. Open VOC project page: https://github.com/beeware/voc
2. Verify badges on the top of README.rst

**Actual result:** beekeeper badge isn't displayed

**Expected result:** beekeeper badge should appear

**Comment:** current image link is `https://beekeeper.herokuapp.com/projects/pybee/voc/shield.` I guess it should point on **.svg** file.

**Comment by whydoubt** [comment]
The fix for this is #948

**Comment by ikostan** [comment]
Thanks, the issue is closed now.
