### ISSUE TITLE
Problem running Hello World tutorial

### ISSUE THREAD

**Issue by kishcs** [beeware/voc#974]
I have followed the steps given in the link below
https://voc.readthedocs.io/en/latest/tutorial/tutorial-0.html

I am trying it in Windows 10.
But at last stage, I am getting error.
```
>java -classpath ../dist/Python-3.7-Java-testdaemon.b7.jar; python.example

Error: Could not find or load main class python.example
Caused by: java.lang.NoClassDefFoundError: org/python/types/Module
```

**Comment by freakboy3742** [comment]
Hi @kishcs! Sorry to hear you're having difficulties.

Firstly, the instruction you've just given isn't the one the tutorial instructs you to run - you should be running:
```
> java -classpath ../voc/dist/python-java-support.jar;. python.example
```
You're missing the `voc` portion of the path, and the full stop after the semicolon but before `python.example`.

If that still doesn't fix the problem, they key thing to check is that you're in the right directory, and the paths you're referencing actually exist. So, from wherever you're runnning the command, the reference to the JAR file should point at a file that exists, and python/example.class should exist as well.

I hope that helps! Let us know if you have any more problems.

**Comment by kishcs** [comment]
Hello @freakboy3742 
I have given dot(.) after semicolon(;), but still I get same error. 
I am running in Windows 10.

Current directory:  `***\voc\voc\tutorial0\`
In this I have `example.py` and `python\example.class`
From here I am giving below command:
`java -classpath ../dist/Python-3.7-Java-testdaemon.b7.jar;. python.example`

and I checked in previous directory i.e. `voc\` contains `dist` with specified jar.
Is there any problem with jar? As I am giving jar which was generated earlier.
Do I need to give `python-java-support.jar` only ?

Please guide me.

**Comment by kishcs** [comment]
Hi @freakboy3742 

I just restarted my terminal window and now it is working.
I am getting output as `hello world`.

Thanks for your time. :)
